#!/usr/bin/perl

#######################################################################
#            The following are customizable parameters.               *
#######################################################################

# FIBS users who are denied use of the bot due to antisocial
# behavior or attempted cheating.
#
%assholes = (
# testing
#	'test' => 1,
# jackdaddy
	'jackdaddy' => 1,
# oystein's bot
	'octopus' => 1,
# djkc (lifted june 25th 2016, next round = 8 weeks)
# djkc (restored jan 11th 2017, next round = 16 weeks)
#	'djkc' => 1,
# pck
	'pck' => 1,
	# 'kellner' => 1,
# DeaDice (nicks expired 20150805, commented out, inim)
#	'DeaDice' => 1,
#	'yourfuturexwife' => 1,
#	'secos' => 1, 
#	'Sequit' => 1,
#	'lump' => 1,
#	'rincon' => 1,
#	'yopow' => 1,
#	'Jezebel' => 1,
#	'JezTester' => 1,
#	'ValleyGirlBOT' => 1, 

# rif_raf	
	'rif_raf' => 1,

# shiva bots
	'bonehead' => 1,
# ???
	'Montecarlo' => 1,
# Phaedrus Bots (commented out expired ones 20161229 and 20180130 inim)
	'Aisopos' => 1,
	'MarianneBot' => 1,
	'maxBrod' => 1,
	'Stats' => 1,
#	'PhaedrusBot' => 1,
#	'Socrates' => 1,
#	'Theages' => 1,
#	'PenelopeBot' => 1,
#	'Protagoras' => 1,
#	'OdysseusBot' => 1,
#	'Gorgias' => 1,
#	'Marianne' =>1,
#	'Tosca' =>1,
#	'dylan' => 1,
#	'Phaedrus' =>1,
# violet313@gmail.com host-92-21-235-86.as13285.net 
#	'pixie' => 1,
#	'goblin' => 1,

# marekful bots
#	'MatchDog' => 1,
#	'MatchDogMini' => 1,

# bot owner of bonehead
	#'shiva' => 1,

# Gaissenpeter
# 'geissenpeter' => 1,
# 'gaissenpeter' => 1,
#'Wizzard_of_Ozz' => 1,
#'burperKing' => 1,
#'straycat' => 1,
#'blattwerk' => 1,
#'GaissenPeter' => 1,
#'geissenpeTer' => 1,
#'Gerstensaftsauger' => 1,
#'underdog' => 1,
#'dieLinke' => 1,
#'Steinlaus' => 1,
#'contreras' => 1,
#'Klangprobe' => 1,
#'StuttgartOpen' => 1,
#'Schaffkopf' => 1,
#'Eierwiesel' => 1,
#'hss' => 1,
#'Tatzelwurm' => 1,
#'bardancer' => 1,
#'carper' => 1,
#'Zehntknecht' => 1,
#'HavanaClub' => 1,
#'Faschingsmuffel' => 1,
#'boggensagg' => 1,
#'frustrator' => 1,
#'poltergeist' => 1,
#'McGrill' => 1,
#'klugscheisser' => 1,
#'bienaagoggerer' => 1,
#'Schwarzbrenner' => 1,
#'wenzmann' => 1,
#'strayraccoon' => 1,
#'kls' => 1,
#'Saustecher' => 1,
#'Sofabolschewik' => 1,
#'osrentador' => 1,
#'CarloMonte' => 1,
#'Zottelbock' => 1,
#'WiWa' => 1,
#'kerwa' => 1,
#'goatherder' => 1,
#'Scheisshaussepp' => 1,
#'MariaBonita' => 1,
#'randydickweed' => 1,
#'Sumpfhuhn' => 1,
#'MindestlohnZehnEURO' => 1,
#'velocipedista' =>1,
#'Muggendorfer' => 1,
#'Nachteule' => 1,
#'gBOTsimple' => 1,
#'Schichtwechsel' => 1,
#'dxm' => 1,
#'ECOfibster' => 1,
#'justcallmeboss' => 1,
#'baldanders' => 1,
#'ZZZ' => 1,
#'Nichtraucher' => 1,
#'JlJ' => 1,
#'Camille' => 1,
#'aussenHaut' => 1,
#'greedhead' => 1,
#'lemaraudeur' => 1,
#'Rauschbeere' => 1,
#'Hoderlump' => 1,
#'dickhead' => 1,
#'gaensla' => 1,
#'Lampenwart' => 1,
#'voucher' => 1,
#'Schwarzwurst' => 1,
#'Steinmetz' => 1,
#'gasguzzler' => 1,
#'Mowgli' => 1,
#'catkicker' => 1,
#'AliBaba' => 1,
#'blundererinchief' => 1,
#'ichmachdichplatt' => 1,
#'TANCATPERVACANCES' => 1,
#'Spielratz' => 1,
#'rumpelStilzchen' => 1,
#'enigMA' => 1,
#'FlakyPhoneUser' => 1,
#'Rauschbeere' => 1,
#'ambidexter' => 1,
#'brokenarrow' => 1,
#'yeoman' => 1,
#'plaerdemavida' => 1,
#'Steinmetz' => 1,
#'Sackgeld' => 1,
#'Kohlsuppe' => 1,
#'tiquismiquis' => 1,
#'gammonhog' => 1,
#'AguilaRoja' => 1,
#'Carpanta' => 1,
#'abejero' => 1,
#'sinrumbofijo' => 1,
#'ratoncito' => 1,
#'apl' => 1,
#'erlich' => 1,
#'naschkatze' => 1,
#'shabbesgoy' => 1,
#'echtschweingehabt' => 1,
#'Raucherschutzgebiet' => 1,
#'Negerkuss' => 1,
#'anm' => 1,
#'expector' => 1,
#'oldrattler' => 1,
#'uayor' => 1,
#'Ochsensepp' => 1,
#'DonQuixote' => 1,
#'wintergreen' => 1,
#'BlendeAcht' => 1,
#'Rosskastanie' => 1,
#'obenbleiben' => 1,
#'masterofblunder' => 1,
#'Plaudertasche' => 1,
#'vellmajoral' => 1,
#'magisterludi' => 1,
#'gatvell' => 1,
#'NIHILessesuperfluum' => 1,
#'GreenFairy' => 1,
#'linuxfux' => 1,
#'Scholar' => 1,
#'chatnoir' => 1,
#'Querholz' => 1,
#'jcmb' => 1,
#'RentoKiller' => 1,
#'oJo' => 1,
#'Toppler' => 1,
#'zlatnapcela' => 1,
#'vollimsoll' => 1,
#'muggi' => 1,
#'opferziege' => 1,
#'Modulok' => 1,
#'Aasgeierkapitalist' => 1,
#'Silberfuchs' => 1,
#'CapitanoOrsoBlue' => 1,
#'Samtpfote' => 1,

#'Querkopf' => 1,
#'gamsjager' => 1,
#'Schwarzarbeiter' => 1,
#'Jennerwein' => 1,
#'overreactor' => 1,
#'Hosenscheisser' => 1,
#'LuckyHal' => 1,
#'BlackHatShadowman' => 1,
#'elmetec' => 1,

#'argus' => 1,
#'oquita' => 1,
#'crackberry' => 1,
#'falc' => 1,

#'nobshen' => 1,
#'sudhir' => 1,
#'sakir' => 1,

#'niFlickFlock' => 1,
# mossab?
#'Monkey' => 1,
#'ramiz' => 1,
#'vogonpoet' => 1,
#'hans' => 1,
#'Gernot' => 1,
#'mucky' => 1,
#'KasparHauser' => 1,
#'Weihnachtsmuffel' => 1,

#'anm' => 1,
#'anynou' => 1,
#'avecplaisir' => 1,
#'bouc' => 1,
#'fidany' => 1,
#'gUSAno' => 1,
#'hexla' => 1,

#'Nimmersatt' => 1,
#'cazadorsolitario' => 1,
#'Mutti' => 1,
#'gogul' => 1,
#'ulmis' => 1,
#'wrltheiv' => 1,

#'ressaguer' => 1,
#'_under_score_dog_' => 1,
#'cJc' => 1,
#'loncleEnric' => 1,
#'seilschafter' => 1,

#'blindfux' => 1,
#'elconquistador' => 1,
#'garza' => 1,
#'qsw' => 1,
#'CapitanOsBlau' => 1,
#'lebouliste' => 1,
#'urraca' => 1,
#'Sauhund' => 1,
#'cabrito' => 1,
#'gls' => 1,
#'Matrizenschlosser' => 1,
#'boletaire' => 1,

#'RoteEule' =>  1,
#'kaskopp' => 1,
#'outilleur' => 1,
#'merda' => 1,
#'erich' => 1,
#'Henri' => 1,
#'beiekuerf' => 1,
#'ferrer' => 1,
#'Miguelito' => 1,
#'elquinto' => 1,
#'sidie' => 1,
#'RoteEUle' => 1,
#'Hanzy' => 1,
#'Emma' => 1,
#'sanm' => 1,
#'anm' => 1,
#'reitstiefel' => 1,
#'lederteufel' => 1,
#'nild' => 1,
#'lloba' => 1,
#'blth' => 1,
#'cel' => 1,
);

#######################################################################
#                 End of customizable parameters.                     *
#######################################################################

